apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: tf-dlrm-benchmark
  namespace: default
spec:
  replicatedJobs:
    - name: worker
      replicas: 8
      template: # This is the Job template
        spec:
          template: # This is the Pod template spec
            metadata:
              annotations:
                gke-gcsfuse/volumes: "true"
            spec: # This is the Pod spec
              serviceAccountName: tpu-training-sa
              restartPolicy: Never
              nodeSelector:
                cloud.google.com/gke-tpu-topology: 4x8
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
              volumes:
              - name: gcs-fuse-csi-volume
                csi:
                  driver: gcsfuse.csi.storage.gke.io
                  volumeAttributes:
                    bucketName: ${BUCKET_NAME}
                    mountOptions: "implicit-dirs"
              containers:
              - name: tf-keras-dlrm
                image: us-east5-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/tf-dlrm-gke:latest
                imagePullPolicy: "Always"
                volumeMounts:
                - name: gcs-fuse-csi-volume
                  mountPath: /gcs
                env:
                - name: BUCKET_NAME
                  value: ${BUCKET_NAME}
                resources:
                  limits:
                    google.com/tpu: 4
                securityContext:
                  privileged: true
  failurePolicy:
    maxRestarts: 0
