apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jax-dlrm-benchmark-v4-8chip
  namespace: default
spec:
  replicatedJobs:
    - name: worker
      replicas: 1
      template:
        spec:
          template:
            metadata:
              annotations:
                gke-gcsfuse/volumes: "true"
            spec:
              serviceAccountName: tpu-training-sa
              restartPolicy: Never
              nodeSelector:
                cloud.google.com/gke-tpu-topology: 4x8
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
              volumes:
              - name: gcs-fuse-csi-volume
                csi:
                  driver: gcsfuse.csi.storage.gke.io
                  volumeAttributes:
                    bucketName: ${BUCKET_NAME}
                    mountOptions: "implicit-dirs"
              containers:
              - name: jax-keras-dlrm
                image: us-east5-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/jax-dlrm-gke:latest
                imagePullPolicy: "Always"
                volumeMounts:
                - name: gcs-fuse-csi-volume
                env:
                - name: TRAIN_DATA_PATH
                  value: "gs://zyc_dlrm/dataset/tb_tf_record_train_val/train/day_*/*"
                - name: EVAL_DATA_PATH
                  value: "gs://zyc_dlrm/dataset/tb_tf_record_train_val/eval/day_*/*"
                resources:
                  limits:
                    google.com/tpu: 8
                securityContext:
                  privileged: true
  failurePolicy:
    maxRestarts: 0
