apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jax-dlrm-singlenode-test
  namespace: default
spec:
  replicatedJobs:
    - name: worker
      # 1. Run on a single replica (one pod)
      replicas: 1
      template:
        spec:
          template:
            metadata:
              annotations:
                gke-gcsfuse/volumes: "true"
            spec:
              serviceAccountName: tpu-training-sa
              restartPolicy: Never
              nodeSelector:
                # 2. Target a single-node 2x4 topology
                cloud.google.com/gke-tpu-topology: 2x2
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
              volumes:
              - name: gcs-fuse-csi-volume
                csi:
                  driver: gcsfuse.csi.storage.gke.io
                  volumeAttributes:
                    # Use the hardcoded bucket name
                    bucketName: "dlrm-training-chavoshi-gke-dev"
                    mountOptions: "implicit-dirs"
              containers:
              - name: jax-keras-dlrm
                image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/jax-dlrm-gke:latest
                imagePullPolicy: "Always"
                volumeMounts:
                - name: gcs-fuse-csi-volume
                  mountPath: /gcs
                env:
                # 3. JAX distributed env vars are removed for single-node run
                - name: TRAIN_DATA_PATH
                  value: "/gcs/synthetic_data/train/*"
                - name: EVAL_DATA_PATH
                  value: "/gcs/synthetic_data/eval/*"
                resources:
                  limits:
                    google.com/tpu: 4 # A 2x4 node has 4 TPU chips
                securityContext:
                  privileged: true
  failurePolicy:
    maxRestarts: 0
