apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jax-dlrm-singlenode-test
  namespace: default
spec:
  replicatedJobs:
    - name: worker
      # 1. Run on a single replica (one pod)
      replicas: 1
      template:
        spec:
          template:
            metadata:
              # 2. Removed GCS Fuse annotation
              annotations: {}
            spec:
              serviceAccountName: tpu-training-sa
              restartPolicy: Never
              nodeSelector:
                cloud.google.com/gke-tpu-topology: 2x2
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
              containers:
              - name: jax-keras-dlrm
                image: us-east5-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/jax-dlrm-gke:latest
                imagePullPolicy: "Always"
                env:
                - name: TRAIN_DATA_PATH
                  value: "gs://zyc_dlrm/dataset/tb_tf_record_train_val/train/day_*/*"
                - name: EVAL_DATA_PATH
                  value: "gs://zyc_dlrm/dataset/tb_tf_record_train_val/eval/day_*/*"
                resources:
                  limits:
                    google.com/tpu: 4 # A 2x4 node has 4 TPU chips
                securityContext:
                  privileged: true
  failurePolicy:
    maxRestarts: 0
