# headless-service.yaml
# This headless service is required for DNS discovery between the pods
# in the multi-host JAX training job. It works with the `subdomain`
# field in the job specification.

apiVersion: v1
kind: Service
metadata:
  # The service name must match the `subdomain` in the Job spec
  name: tpu-job 
  namespace: default
spec:
  # clusterIP: None makes this a "headless" service, which is used for DNS discovery
  clusterIP: None
  # This selector must match the labels of the pods created by the Job
  selector:
    job-name: lora-finetuning-job-jax-4x4
