apiVersion: batch/v1
kind: Job
metadata:
  name: lora-finetuning-job
spec:
  template:
    spec:
      serviceAccountName: tpu-training-sa
      containers:
      - name: training-container
        image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tpu-lora-trainer:v17
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: token
        command: ["xla_dist"]
        args: [
          "--num-gpus=4", # Corresponds to the number of TPU chips
          "--",
          "python",
          "train.py",
          "--dataset_path", "gs://your-bucket-name/processed_data", # <-- Replace with your BUCKET_NAME
          "--output_dir", "gs://your-bucket-name/output" # <-- Replace with your BUCKET_NAME
        ]
        resources:
          limits:
            google.com/tpu: 4
        securityContext:
          privileged: true
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 2x2
      restartPolicy: Never
  backoffLimit: 1
