apiVersion: batch/v1
kind: Job
metadata:
  name: lora-finetuning-job
spec:
  template:
    spec:
      serviceAccountName: tpu-training-sa
      containers:
      - name: training-container
        image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tpu-lora-trainer-jax:latest
        imagePullPolicy: "Always"
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: token
        - name: TRANSFORMERS_VERBOSITY
          value: "info"
        command: ["python", "train.py"]
        args: [
          "--dataset_path", "gs://lora-finetuning-data-chavoshi-gke-dev/processed_data",
          "--gcs_output_dir", "gs://lora-finetuning-data-chavoshi-gke-dev/output-jax"
        ]
        resources:
          limits:
            google.com/tpu: 4
        securityContext:
          privileged: true
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 2x2
      restartPolicy: Never
  backoffLimit: 1
