# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: lora-finetuning-job
spec:
  template:
    # --- The metadata block with annotations belongs here ---
    # It is a sibling of the pod's 'spec', not a child of it.
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: tpu-training-sa
      volumes:
      - name: gcs-fuse-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: lora-finetuning-data-chavoshi-gke-dev
            mountOptions: "implicit-dirs"
      containers:
      - name: training-container
        image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tpu-lora-trainer-jax:latest
        imagePullPolicy: "Always"
        volumeMounts:
        - name: gcs-fuse-volume
          mountPath: /gcs
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: token
        - name: TRANSFORMERS_VERBOSITY
          value: "info"
        command: ["python", "train.py"]
        args: [
          "--dataset_path", "/gcs/processed_data",
          "--output_dir", "/gcs/trained_lora_model"
        ]
        resources:
          limits:
            google.com/tpu: 4
        securityContext:
          privileged: true
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 2x2
      restartPolicy: Never
  backoffLimit: 1
