apiVersion: batch/v1
kind: Job
metadata:
  name: lora-finetuning-job-jax-single-node
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      serviceAccountName: tpu-training-sa
      containers:
      - name: training-container
        image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tpu-lora-trainer-jax:v5
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: token
        - name: JAX_PLATFORMS
          value: "tpu"
        command: ["python", "train_jax.py"]
        args: [
          "--dataset_path", "gs://lora-finetuning-data-chavoshi-gke-dev/processed_data",
          "--output_dir", "gs://lora-finetuning-data-chavoshi-gke-dev/output-jax"
        ]
        resources:
          limits:
            google.com/tpu: 4
        securityContext:
          privileged: true
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 2x2
      restartPolicy: Never
  backoffLimit: 1
