apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lora-chat
  template:
    metadata:
      labels:
        app: lora-chat
    spec:
      serviceAccountName: lora-serving-sa
      containers:
      - name: chat-container
        image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/lora-chat:latest
        command: ["python", "chat.py"]
        args: [
          "--gcs_lora_adapter_path",
          "gs://lora-finetuning-data-chavoshi-gke-dev/trained_lora_model/checkpoint-21"
        ]
        tty: true
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: token
        resources:
          limits:
            google.com/tpu: 4
            memory: "64Gi" 
          requests:
            # And add a memory request as well
            memory: "64Gi"
        securityContext:
          privileged: true
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
        cloud.google.com/gke-tpu-topology: 2x2
