# worker-inspector-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: worker-image-inspector-pod
spec:
  containers:
  - name: inspector
    # This is your colleague's working worker image
    image: us-west1-docker.pkg.dev/tpu-vm-gke-testing/kevinmcw-repo/dlrm:worker219
    # We override the default entrypoint with our inspection script
    command:
      - "bash"
      - "-c"
      - |
        set -e
        echo "✅✅✅ STARTING WORKER IMAGE INSPECTION ✅✅✅"
        
        echo "\n\n--- 1. ENVIRONMENT VARIABLES ---"
        printenv | sort
        
        echo "\n\n--- 2. INSTALLED PYTHON PACKAGES (pip list) ---"
        pip list
        
        echo "\n\n--- 3. SCRIPT CONTENTS ---"
        # The worker Dockerfile copies its script here
        SCRIPT_PATH="/usr/local/bin/tpu_tfjob_worker.sh"
        echo "--> Checking for ${SCRIPT_PATH}..."
        if [ -f "${SCRIPT_PATH}" ]; then
            echo "--- Contents of ${SCRIPT_PATH} ---"
            cat "${SCRIPT_PATH}"
        else
            echo "File ${SCRIPT_PATH} not found."
        fi
        
        echo "\n\n✅✅✅ INSPECTION COMPLETE ✅✅✅"
  
  # This ensures the pod stops after the command is done.
  restartPolicy: Never
