apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: ${TFJOB_NAME}
spec:
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 600
  tfReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: ExitCode
      template:
        metadata:
          labels:
            app: tfjob
          annotations:
            gke-gcsfuse/volumes: "true"
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: chavoshi-dlrm-job-sa
          volumes:
            - name: gcs-fuse-volume
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: ${GCS_BUCKET_NAME}
                  mountOptions: "implicit-dirs,file-cache:max-size-mb:-1,file-cache:enable-parallel-downloads:true,read_ahead_kb=1024,metadata-cache:ttl-secs:-1"
          containers:
            - name: tensorflow
              volumeMounts:
                - name: gcs-fuse-volume
                  mountPath: /gcs
              command:
                - bash
                - -c
                - |
                  echo "--- Starting Master Pod ---"
                  echo "Waiting for all 32 worker pods to become DNS resolvable..."
                  sleep 30s

                  echo "✅ All workers are ready. Starting TensorFlow training..."
                  # Restored original multi-line format for readability
                  TF_USE_LEGACY_KERAS=1 TPU_LOAD_LIBRARY=0 TF_XLA_FLAGS="--tf_mlir_enable_mlir_bridge=true \
                  --tf_xla_sparse_core_disable_table_stacking=true \
                  --tf_mlir_enable_convert_control_to_data_outputs_pass=true \
                  --tf_mlir_enable_merge_control_flow_pass=true" python3 /models/official/recommendation/ranking/train.py  --mode=train     --model_dir="/gcs/v6e_128/" --params_override="
                  runtime:
                    distribution_strategy: tpu
                    mixed_precision_dtype: 'mixed_bfloat16'
                    tpu: 'grpc://${TFJOB_NAME}-worker-0.default.svc,grpc://${TFJOB_NAME}-worker-1.default.svc,grpc://${TFJOB_NAME}-worker-2.default.svc,grpc://${TFJOB_NAME}-worker-3.default.svc,grpc://${TFJOB_NAME}-worker-4.default.svc,grpc://${TFJOB_NAME}-worker-5.default.svc,grpc://${TFJOB_NAME}-worker-6.default.svc,grpc://${TFJOB_NAME}-worker-7.default.svc,grpc://${TFJOB_NAME}-worker-8.default.svc,grpc://${TFJOB_NAME}-worker-9.default.svc,grpc://${TFJOB_NAME}-worker-10.default.svc,grpc://${TFJOB_NAME}-worker-11.default.svc,grpc://${TFJOB_NAME}-worker-12.default.svc,grpc://${TFJOB_NAME}-worker-13.default.svc,grpc://${TFJOB_NAME}-worker-14.default.svc,grpc://${TFJOB_NAME}-worker-15.default.svc,grpc://${TFJOB_NAME}-worker-16.default.svc,grpc://${TFJOB_NAME}-worker-17.default.svc,grpc://${TFJOB_NAME}-worker-18.default.svc,grpc://${TFJOB_NAME}-worker-19.default.svc,grpc://${TFJOB_NAME}-worker-20.default.svc,grpc://${TFJOB_NAME}-worker-21.default.svc,grpc://${TFJOB_NAME}-worker-22.default.svc,grpc://${TFJOB_NAME}-worker-23.default.svc,grpc://${TFJOB_NAME}-worker-24.default.svc,grpc://${TFJOB_NAME}-worker-25.default.svc,grpc://${TFJOB_NAME}-worker-26.default.svc,grpc://${TFJOB_NAME}-worker-27.default.svc,grpc://${TFJOB_NAME}-worker-28.default.svc,grpc://${TFJOB_NAME}-worker-29.default.svc,grpc://${TFJOB_NAME}-worker-30.default.svc,grpc://${TFJOB_NAME}-worker-31.default.svc'
                  task:
                    use_synthetic_data: false
                    use_tf_record_reader: true
                    train_data:
                      input_path: '/gcs/tb_tf_record_train_val/tb_tf_record_train_val/train/day_*/*'
                      global_batch_size: 16384
                      use_cached_data: true
                    validation_data:
                      input_path: '/gcs/tb_tf_record_train_val/tb_tf_record_train_val/eval/day_*/*'
                      global_batch_size: 16384
                      use_cached_data: true
                    model:
                      num_dense_features: 13
                      bottom_mlp: [512, 256, 128]
                      embedding_dim: 64
                      interaction: 'multi_layer_dcn'
                      dcn_num_layers: 3
                      dcn_low_rank_dim: 512
                      size_threshold: 8000
                      top_mlp: [1024, 1024, 512, 256, 1]
                      use_multi_hot: true
                      concat_dense: false
                      dcn_use_bias: true
                      vocab_sizes: [40000768,39060,17295,7424,20265,3,7122,1543,63,40000768,3067956,405282,10,2209,11938,155,4,976,14,40000768,40000768,40000768,590152,12973,108,36]
                      multi_hot_sizes: [3,2,1,2,6,1,1,1,1,7,3,8,1,6,9,5,1,1,1,12,100,27,10,3,1,1]
                      max_ids_per_chip_per_sample: 128
                      max_ids_per_table: 4096
                      max_unique_ids_per_table: 2048
                      use_partial_tpu_embedding: false
                      size_threshold: 0
                      initialize_tables_on_host: true
                  trainer:
                    train_steps: 10000
                    validation_interval: 1000
                    validation_steps: 660
                    summary_interval: 1000
                    steps_per_loop: 1000
                    checkpoint_interval: 1000
                    optimizer_config:
                      embedding_optimizer: 'Adagrad'
                      dense_optimizer: 'Adagrad'
                      lr_config:
                        decay_exp: 2
                        decay_start_steps: 70000
                        decay_steps: 30000
                        learning_rate: 0.025
                        warmup_steps: 0
                      dense_sgd_config:
                        decay_exp: 2
                        decay_start_steps: 70000
                        decay_steps: 30000
                        learning_rate: 0.00025
                        warmup_steps: 8000
                    train_tf_function: true
                    train_tf_while_loop: true
                    eval_tf_while_loop: true
                    use_orbit: false
                    pipeline_sparse_and_dense_execution: true"
              image: ${MASTER_IMAGE_URL}
              imagePullPolicy: Always
              env:
                - name: LIBTPU_INIT_ARGS
                  value: "--xla_tpu_embedding_table_oblongness_threshold=inf --copy_with_dynamic_shape_op_output_pjrt_buffer=true"
                - name: TF_JOB_PACKAGE_URIS
                  value: ""
              resources: {}
    Worker:
      replicas: 32
      restartPolicy: ExitCode
      template:
        metadata:
          annotations:
            gke-gcsfuse/volumes: "true"
            sidecar.istio.io/inject: "false"
          labels:
            app: tfjob
        spec:
          serviceAccountName: chavoshi-dlrm-job-sa
          volumes:
            - name: gcs-fuse-volume
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: ${GCS_BUCKET_NAME}
                  mountOptions: "implicit-dirs"
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
            cloud.google.com/gke-tpu-topology: 8x16
          tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: tfjob
            - effect: NoSchedule
              key: google.com/tpu
              operator: Equal
              value: present
          containers:
            - name: tensorflow
              volumeMounts:
                - name: gcs-fuse-volume
                  mountPath: /gcs
              command:
                - bash
                - -c
                - |
                  tpu_tfjob_worker.sh
              env:
                - name: LIBTPU_INIT_ARGS
                  value: "--xla_tpu_embedding_table_oblongness_threshold=inf --copy_with_dynamic_shape_op_output_pjrt_buffer=true"
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: TPU_WORKER_HOSTNAMES
                  value: "tf-128-dlrm-tfjob-gcsfuse-worker-0.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-1.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-2.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-3.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-4.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-5.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-6.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-7.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-8.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-9.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-10.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-11.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-12.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-13.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-14.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-15.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-16.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-17.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-18.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-19.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-20.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-21.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-22.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-23.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-24.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-25.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-26.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-27.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-28.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-29.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-30.default.svc,tf-128-dlrm-tfjob-gcsfuse-worker-31.default.svc"
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['training.kubeflow.org/replica-index']
              image: ${WORKER_IMAGE_URL}
              imagePullPolicy: Always
              resources:
                limits:
                  google.com/tpu: "4"
                requests:
                  google.com/tpu: "4"
