apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: tpu-v5e-training-job
  labels:
    app.kubernetes.io/name: tpu-v5e-training-job
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
    - name: worker
      replicas: 4
      template:
        spec:
          template:
            spec:
              restartPolicy: Never 
              serviceAccountName: tpu-training-sa
              priorityClassName: gke-tpu-preemptible-sc
              containers:
                - name: training-container
                  image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tf-debug-gke:latest
                  resources:
                    limits:
                      google.com/tpu: "4"
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                cloud.google.com/gke-tpu-topology: 4x4
