# tfjob-v6e-16chip.yaml
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: tf-mnist-v6e-16chip
spec:
  runPolicy:
    cleanPodPolicy: Running
  tfReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
            cloud.google.com/gke-tpu-topology: 2x4
          tolerations:
            - key: "google.com/tpu"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
            - name: tensorflow
              image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tf-tpu-unified:latest
              command: ["python", "main.py"]
              # **FIX ADDED HERE**: Manually provide the list of all workers
              # to the low-level TPU driver.
              env:
                - name: TPU_WORKER_HOSTNAMES
                  value: "tf-mnist-v6e-16chip-master-0,tf-mnist-v6e-16chip-worker-0,tf-mnist-v6e-16chip-worker-1,tf-mnist-v6e-16chip-worker-2"
              resources:
                limits:
                  google.com/tpu: "4"
    Worker:
      replicas: 3 # 1 Master + 3 Workers = 4 total nodes
      restartPolicy: OnFailure
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
            cloud.google.com/gke-tpu-topology: 2x4
          tolerations:
            - key: "google.com/tpu"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
            - name: tensorflow
              image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tf-tpu-unified:latest
              command: ["python", "main.py"]
              # **FIX ADDED HERE**: This list must be identical for all pods.
              env:
                - name: TPU_WORKER_HOSTNAMES
                  value: "tf-mnist-v6e-16chip-master-0,tf-mnist-v6e-16chip-worker-0,tf-mnist-v6e-16chip-worker-1,tf-mnist-v6e-16chip-worker-2"
              resources:
                limits:
                  google.com/tpu: "4"
