apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: tpu-movie-ranking-jobset
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-placement: "true"
spec:
  failurePolicy:
    maxRestarts: 3
  replicatedJobs:
    - name: worker
      replicas: 2
      template:
        spec:
          template:
            spec:
              nodeSelector:
                cloud.google.com/gke-tpu-topology: 2x4
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
              containers:
              - name: training-container
                image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/tpu-training-app:v3
                resources:
                  limits:
                    google.com/tpu: 4
              restartPolicy: OnFailure
