apiVersion: batch/v1
kind: Job
metadata:
  name: dlrm-preprocess-job
spec:
  parallelism: 8
  completions: 8
  backoffLimit: 0
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: tpu-training-sa
      restartPolicy: OnFailure
      volumes:
      - name: gcs-fuse-csi-volume
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: ${BUCKET_NAME} # This will be replaced by the script
            mountOptions: "implicit-dirs"
      containers:
      - name: preprocess-worker
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO_NAME}/dlrm-preprocess:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: gcs-fuse-csi-volume
          mountPath: /gcs
        env:
        - name: JOB_COMPLETION_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: PARALLELISM
          value: "8"
        resources:
          requests:
            memory: "800Gi"
            cpu: "180"
          limits:
            memory: "920Gi"
            cpu: "223"

