# jobset.yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: dlrm-jax-experiment
spec:
  replicatedJobs:
  - name: workers
    replicas: 2
    template:
      spec:
        # The pod template starts here
        template:
          spec:
            nodeSelector:
              cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
              cloud.google.com/gke-tpu-topology: 2x2
            containers:
            - name: dlrm-training-container
              image: us-east5-docker.pkg.dev/chavoshi-gke-dev/tpu-repo/dlrm-jax:v3
              resources:
                limits:
                  google.com/tpu: 4
            restartPolicy: Never
            subdomain: dlrm-jax-experiment
