apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: ${JOB_NAME}
spec:
  replicatedJobs:
    - name: worker
      replicas: 4 # 16 chips / 4 chips per pod = 4 pods
      template:
        spec:
          parallelism: 1
          completions: 1
          backoffLimit: 0
          template:
            metadata:
              annotations:
                gke-gcsfuse/volumes: "true"
            spec:
              restartPolicy: Never
              serviceAccountName: chavoshi-dlrm-job-sa
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
                cloud.google.com/gke-tpu-topology: 4x4
              tolerations:
                - key: google.com/tpu
                  operator: Equal
                  value: present
                  effect: NoSchedule
              volumes:
                - name: gcs-fuse-volume
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: ${GCS_BUCKET_NAME}
                      mountOptions: "implicit-dirs"
              containers:
                - name: jax-dlrm
                  image: ${JAX_IMAGE_URL}
                  imagePullPolicy: Always

                  volumeMounts:
                    - name: gcs-fuse-volume
                      mountPath: /gcs
                  # Pass parameters to the main script
                  command:
                    - "python"
                    - "main.py"
                    - "--model_dir=/gcs/jax-checkpoints/v6e-16/"
                    - "--train_data_path=/gcs/tb_tf_record_train_val/tb_tf_record_train_val/train/day_*/*"
                    - "--eval_data_path=/gcs/tb_tf_record_train_val/tb_tf_record_train_val/eval/day_*/*"
                    - "--global_batch_size=16384"
                  resources:
                    limits:
                      google.com/tpu: "4"
                    requests:
                      google.com/tpu: "4"
                  env:
                    - name: JAX_PROCESS_COUNT
                      value: "4"
                    - name: JAX_PRIMARY_ENDPOINT
                      value: "${JOB_NAME}-worker-0-0.${JOB_NAME}:10000"

