apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: ${JOB_NAME}
  labels:
    app.kubernetes.io/name: ${JOB_NAME}
spec:
  replicatedJobs:
    - name: dlrm-job
      replicas: 4 # 16 chips / 4 chips per worker node = 4 replicas
      template:
        spec:
          backoffLimit: 0
          template:
            spec:
              serviceAccountName: chavoshi-dlrm-job-sa
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
                cloud.google.com/gke-tpu-topology: 4x4
              tolerations:
                - key: google.com/tpu
                  operator: Equal
                  value: present
                  effect: NoSchedule
              volumes:
                - name: gcs-fuse-volume
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: ${GCS_BUCKET_NAME}
                      mountOptions: "implicit-dirs"
              containers:
                - name: jax-dlrm-container
                  image: ${JAX_IMAGE_URL}
                  imagePullPolicy: Always
                  command: ["python3", "/app/train_jax.py"]
                  args:
                    - --train_data_path=/gcs/tb_tf_record_train_val/tb_tf_record_train_val/train/day_*/*
                    - --eval_data_path=/gcs/tb_tf_record_train_val/tb_tf_record_train_val/eval/day_*/*
                    - --global_batch_size=16384
                    - --train_steps=1000
                    - --eval_steps=100
                  volumeMounts:
                    - name: gcs-fuse-volume
                      mountPath: /gcs
                      readOnly: true
                  resources:
                    limits:
                      google.com/tpu: "4"
                    requests:
                      google.com/tpu: "4"
              restartPolicy: Never
