# This file is now corrected to strictly follow the official Google Cloud
# documentation for a multi-host TPU JobSet on GKE.

# Key changes based on the guide:
# 1. Removed all manual `JAX_PROCESS_ID`, `JAX_PROCESS_COUNT`, and
#    `JAX_COORDINATOR_ADDRESS` environment variables.
# 2. Added `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet` to
#    give pods direct access to the node's network for easier discovery.
# 3. Added the `exclusive-topology` annotation as recommended for stability.
# 4. Added container ports for TPU communication and metrics.
# 5. Added a privileged security context, which is often necessary for host networking.
# 6. Added JAX-specific environment variables for platform compatibility.
# 7. Added `parallelism`, `completions`, and `failurePolicy` for better job management.
# 8. All setup (pip installs, script modifications) has been moved into the
#    Dockerfile for a more robust, self-contained container.
# 9. Added TPU_NAME environment variable to match the successful TPU VM run.

apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: ${JOB_NAME}
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
spec:
  failurePolicy:
    maxRestarts: 1
  replicatedJobs:
    - name: dlrm-job
      replicas: 1
      template:
        spec:
          backoffLimit: 0
          completions: 4
          parallelism: 4
          template:
            # Added annotation from the official guide for node placement stability.
            metadata:
              annotations:
                gke-gcsfuse/volumes: "true"
            spec:
              # Following the guide's networking model for multi-host JobSets.
              hostNetwork: true
              dnsPolicy: ClusterFirstWithHostNet
              serviceAccountName: chavoshi-dlrm-job-sa
              nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
                cloud.google.com/gke-tpu-topology: 4x4
              tolerations:
                - key: google.com/tpu
                  operator: Equal
                  value: present
                  effect: NoSchedule
              volumes:
                - name: gcs-fuse-volume
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: ${GCS_BUCKET_NAME}
                      mountOptions: "implicit-dirs,file-cache:max-size-mb:-1,file-cache:enable-parallel-downloads:true,read_ahead_kb=1024,metadata-cache:ttl-secs:-1"
              containers:
                - name: jax-dlrm
                  image: ${JAX_IMAGE_URL}
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 8471
                  - containerPort: 8080
                  - containerPort: 8431
                  securityContext:
                    privileged: true
                  # The command now simply executes the script baked into the container.
                  command: ["/app/train_and_checkpoint.sh"]
                  volumeMounts:
                    - name: gcs-fuse-volume
                      mountPath: /gcs
                      readOnly: false
                  env:
                    # Dynamically set the model directory based on the JobSet name
                    - name: MODEL_DIR
                      value: "/gcs/benchmark/model-output/${JOB_NAME}"
                    # This name is used by the training script.
                    - name: TPU_NAME
                      value: "${TPU_POOL_NAME}"
                    - name: JAX_PLATFORMS
                      value: "tpu"
                    - name: ENABLE_PJRT_COMPATIBILITY
                      value: "true"
                  resources:
                    limits:
                      google.com/tpu: "4"
                    requests:
                      google.com/tpu: "4"
              restartPolicy: Never

